GET http://localhost:8001/params/17?nom=hola
Accept-Language: cristino

###

GET http://localhost:8001/params/17?nom=hola
Accept-Language: es-es
Accept: text/xml
###

GET  http://localhost:8001/salida
Accept-Language: es-es
Accept: text/plain, application/json

###

POST  http://localhost:8001/salida
Accept-Language: es-es
Accept: text/plain, application/json
Content-Type: application/json

{
    "id":7,
    "nombre":"Nuevo",
    "apellidos":"Actor"
}

###

POST  http://localhost:8001/salida
Accept-Language: es-es
Accept: text/plain, application/json
Content-Type: application/xml

<ActorDTO>
  <id>0</id>
  <nombre>Pepito</nombre>
  <apellidos>Grillo</apellidos>
</ActorDTO>
###

get  http://localhost:8001/actores

###

get  http://localhost:8001/actores/1/peliculas


###

get  http://localhost:8001/actores?page=0&size=10&sort=firstName

###

post http://localhost:8001/actores/3
Content-Type: application/json

{
  "id": 0,
  "nombre": "",
  "apellidos": "coton"
}

###

put http://localhost:8001/actores/206
Content-Type: application/json

{
  "id": 206,
  "nombre": "CARMELO",
  "apellidos": "COTON"
}

###

delete  http://localhost:8001/actores/206

###

get  http://localhost:8010/actores
Content-Type: application/json
###

get  http://localhost:8010/actores/1/peliculas
Content-Type: application/json
###

get  http://localhost:8010/actores?page=0&size=10&sort=firstName
Content-Type: application/json

###

GET http://localhost:8010/actores/8
Content-Type: application/json

###
post http://localhost:8010/actores
Content-Type: application/json

{
  "id": 330,
  "nombre": "Pollo",
  "apellidos": "Corrar"
}


###

get  http://localhost:8010/actores/330
Content-Type: application/json
