   
env:
  browser: true
  es2021: true
  jasmine: true
plugins:
  - jasmine
extends: 
  - 'plugin:jasmine/recommended'
  - 'eslint:recommended'
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  no-unused-vars: warn