server:
  port: ${PORT:8080}
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: false
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    appname: apigateway-server
spring:
  application:
    name: apigateway-server
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
      - id: serv-catalogo
          #lb:// cuando se va a acceder a través de Eureka
        uri: lb://catalogo-service
        predicates:
          - Path=/catalogo/**
        filters:
          - RewritePath=/catalogo/*, /
          - RewriteLocationResponseHeader=AS_IN_REQUEST, Location, ,
      - id: serv-demos
        uri: lb://demo-service
        predicates:
          - Path=/demos/**
        filters:
          - RewritePath=/demos/*, /
      - id: serv-contatos
        uri: lb://contactos-service
        predicates:
          - Path=/contactos/**
        filters:
          - RewritePath=/contactos/, /api/contactos
      - id: serv-search
        uri: https://www.google.com/
        predicates:
          - Path=/search/**
        filters:
          - RewritePath=/search/*, /
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
